# -*- mode: ruby -*-
# vi: set ft=ruby :
$script = <<SCRIPT
# Update apt and get dependencies
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python-pip
pip install flask
pip install flask-mysql
#python /test/app.py &
echo "Hello hamed" > ~/test.txt
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.synced_folder "./FlaskApp", "/FlaskApp"
  config.vm.provision "shell", inline: $script, privileged: false
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
  # documentation for more information about their specific syntax and use.
  #config.vm.provision "shell", inline: <<-SHELL
  #  apt-get update
  #  apt-get install -y apache2
  #SHELL
end
